"""add_customers_table

Revision ID: 5887fc2c37f6
Revises: d5e6f7a8b9c0
Create Date: 2026-08-10 16:15:53.169504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5887fc2c37f6"
down_revision: str | Sequence[str] | None = "d5e6f7a8b9c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "token_hash",
        existing_type=sa.VARCHAR(length=64),
        comment="SHA-256 hash of refresh token",
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "family_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Token family ID (one per login session)",
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "created_ip",
        existing_type=sa.VARCHAR(length=45),
        comment="Client IP for audit",
        existing_nullable=True,
    )
    op.alter_column(
        "refresh_tokens",
        "user_agent",
        existing_type=sa.VARCHAR(length=500),
        comment="User-Agent for audit",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "user_agent",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="User-Agent for audit",
        existing_nullable=True,
    )
    op.alter_column(
        "refresh_tokens",
        "created_ip",
        existing_type=sa.VARCHAR(length=45),
        comment=None,
        existing_comment="Client IP for audit",
        existing_nullable=True,
    )
    op.alter_column(
        "refresh_tokens",
        "family_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Token family ID (one per login session)",
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "token_hash",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="SHA-256 hash of refresh token",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
