"""add_oauth2_fields_to_users

Revision ID: f5f5cf021538
Revises: 5887fc2c37f6
Create Date: 2026-08-11 09:56:17.117875

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5f5cf021538"
down_revision: str | Sequence[str] | None = "5887fc2c37f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=100), nullable=True))
    # Add auth_provider as nullable first, set default, then make NOT NULL
    op.add_column(
        "users", sa.Column("auth_provider", sa.String(length=20), nullable=True)
    )
    op.execute("UPDATE users SET auth_provider = 'local' WHERE auth_provider IS NULL")
    op.alter_column("users", "auth_provider", nullable=False)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
